language: python

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - make test-unit
  - docker-compose up -d
  - sleep 5
  - python setup.py install
  - make test-functional
