language: python

services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - make test-unit
  - make start-functional-stack
  - python setup.py install
  - make test-functional
