language: python

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - make test-unit
  - docker-compose up -d
  - sleep 5
  - python bin/funcy-task-engine.py xmltest -t tests/funcy/uuid-nsq-postgres.yml
